export const data = {
    mentors: [
        {
            src: '/JP_SAINI_SIR.jpg',
            name: 'Prof. J.P. Saini',
            position: 'Professor',

        },
        {
            src: '/SP_SINGH_SIR.jpg',
            name: 'Prof. S.P. Singh',
            position: 'Professor',

        },
        {
            src: '/Dr.D.S.Singh.jpg',
            name: 'Prof. D.S. Singh',
            position: 'Professor',

        },
    ],
    dev: [
        {
            src: '/adityagaur.jpg',
            name: 'Aditya Gaur',
            branch: 'CSE 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
        {
            src: '/Tejas.jpg',
            name: 'Tejas Mishra',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
        {
            src: '/SandeepSingh.jpg',
            name: 'Sandeep Singh',
            branch: 'ECE 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
        {
            src: '/Anmol.jpg',
            name: 'Anmol Tripathi',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
        {
            src: '/prachi.jpeg',
            name: 'Prachi Patel',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
        {
            src: '/jyoti.jpg',
            name: 'Jyoti Maurya',
            branch: 'CSE 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },

        {
            src: '/anjul.jpg',
            name: 'Anjul Singh',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
        {
            src: '/Prabhat.jpeg',
            name: 'Prabhat Yadav',
            branch: 'CSE 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
        {
            src: '/hv.jpg',
            name: 'Himanshu Verma',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',

        },
    ],
    content: [
        {
            src: '/Rudra.jpg',
            name: 'Rudra Dubey',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/aashi.jpeg',
            name: 'Aashi Awasthi',
            branch: 'ECE 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/Harsh.jpeg',
            name: 'Harsh Agrahari',
            branch: 'CSE 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/AbhayECE.jpeg',
            name: 'Abhay Tirthanker',
            branch: 'ECE 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/Vishal.jpeg',
            name: 'Vishal Tiwari',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/priya.jpg',
            name: 'Priya',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/Manoj.jpg',
            name: 'Manoj Kumar',
            branch: 'IT 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/Anurag.jpg',
            name: 'Anurag Singh',
            branch: 'ME 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/Akshara.jpeg',
            name: 'Akshara',
            branch: 'BPharm. 2026',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/Sneha.jpeg',
            name: 'Sneha',
            branch: 'Chemical',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/anupam.jpg',
            name: 'Anupam Tiwari',
            branch: 'BPharm.',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/kartik.jpg',
            name: 'Kartik Katiyar',
            branch: 'BBA',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: 'https://mmmut.xyz/teamimg/adityapatel.jpeg',
            name: 'Aditya Patel',
            branch: 'BPharm.',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
        {
            src: '/krish.jpg',
            name: 'Krishna Chaurasiya',
            branch: 'BBA',
            linkedin: '',
            instagram: '',
            mail: '',
            whatsapp: '',
        },
    ]
}